name: Feature Request
description: Propose an improvement
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Problem
      description: What problem are you solving?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
      description: Describe your proposed change
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives Considered
      description: Other options you considered
